#--------------------------------------------------------------
# config 
ENTRY_PATH="./.github/workflows"
ACTION_URL="https://github.com/tmslpm/Collection-Github-Action/actions/workflows/"
RAW_URL="https://raw.githubusercontent.com/tmslpm/Collection-Github-Action/main/.github/workflows/"
URL="https://github.com/tmslpm/Collection-Github-Action/blob/main/.github/workflows/" 
BACK_TO_TOP="<pre align=center>↑↑↑ <a href='#-collection-github-action' title='click to scroll up' alt='click to scroll up'>BACK TO TOP</a> ↑↑↑</pre>"

#--------------------------------------------------------------
# get all workflows in repos
RESULT=$(ls $ENTRY_PATH)
 
#--------------------------------------------------------------
# append all action title + link in variable 
arrTableList="" && strList="" && indexCategory=0 
for f in $RESULT; do
    # title
    title=$(cat "${ENTRY_PATH}/${f}" | grep "^# name:") && title="${title/\# name:/''}"
    # description
    description=$(cat "${ENTRY_PATH}/${f}" | grep "# description:") && description="${description/\# description:/''}"
    # category
    currentCategory=$(cat "${ENTRY_PATH}/${f}" | grep "^# category:") && currentCategory="${currentCategory/\# category: /''}" 
 
    # check if is a new category
    hasNotFoundCategory=true
    for k in "${!category[@]}"; do 
        if [[ "${category[$k]}" == $currentCategory ]]; then
            hasNotFoundCategory=false
            break
        fi 
    done

    # if new register
    if $hasNotFoundCategory; then
        category[$indexCategory]="${currentCategory}" && ((indexCategory=indexCategory+1))
    fi
    
    # build list html
    for k in "${!category[@]}"; do  
        if [[ "${category[$k]}" == $currentCategory ]]; then
            arrTableList[$k]="${arrTableList[$k]} <li><a href='#-${title// /-}' title='go to ${title}'>${title}</a></li>"
            break
        fi 
    done 
    
    strList="${strList}\
        <h2>🟢 ${title}</h2>\
        <p>${description}</p>\
        <p style="text-align:center" align="center">\
        🔗 \
        - <a href='${URL}${f}' title='open the source code of the action'>SOURCE</a>\
        - <a href='${RAW_URL}${f}' title='open the raw code of the action'>RAW</a>\
        - <a href='${ACTION_URL}${f}' title='open the the action'>ACTION</a>\
        - 🔗</p><p style="text-align:center" align="center">\
        <img src='${ACTION_URL}${f}/badge.svg' alt='badge action/${f}@main'/>\
        </p>${BACK_TO_TOP}"
done
  
#--------------------------------------------------------------
# write in readme

for k in "${!arrTableList[@]}"; do 
    strTable="${strTable} <h4>✨ ${category[$k]}</h4> ${arrTableList[$k]}"
done
 
echo "\
<p style="text-align:center" align="center">readme generated on $(date "+%H:%M:%S at %d/%m/%y")</p><hr>\
<h1>🚀 Collection Github Action</h1>\
<p>Goal: create a small collection of Github Action examples. You'll find the various actions in the <code>.github/workflows</code> folder or you can navigate using the menu below.</p>\
<p>🏴 This readme is generated by a shell script (<code>./generateReadme.sh</code>). If you wish to contribute and add an action to the repository, be sure to consult the <code>contributing.md</code> guide in the <code>./docs</code> folder.</p>
<h2>Table</h2>\
${strTable}\
${strList}\
<hr><p style="text-align:center" align="center">readme generated on $(date "+%H:%M:%S at %d/%m/%y")</p>\
" > README.md