# task/action name/descrption
name: build
run-name: ${{ github.actor }} - example gh api get gist
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          RESPONSE_API=$(curl -L\
            -H "Accept: application/vnd.github+json"\
            -H "Authorization: token ${{ secrets.PAT }}"\
            -H "X-GitHub-Api-Version: 2022-11-28"\
            https://api.github.com/users/tmslpm/gists)
          echo $RESPONSE_API > gist_data.last.json 
  call-push:
    uses: ./.github/workflows/call/push.tasks.yml