# task/action name/descrption
name: ▶️ get all gist 
run-name: ${{ github.actor }} - example gh api get gist
on: workflow_dispatch
jobs:
  # - - - - - - - - - - - - - - - - - - - - - -
  # use the gh api to get all gists and store the response in a json file
  main:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          RESPONSE_API=$(curl -L\
            -H "Accept: application/vnd.github+json"\
            -H "Authorization: token ${{ secrets.PAT }}"\
            -H "X-GitHub-Api-Version: 2022-11-28"\
            https://api.github.com/users/tmslpm/gists)
          echo $RESPONSE_API > dist/gist_data.last.json
          
  # - - - - - - - - - - - - - - - - - - - - - -
  # Call .github/workflows/call.push.tasks.yml
  call-push:
    uses: tmslpm/My-Collection-Github-Action/.github/workflows/call.push.tasks.yml@main