name: ▶️ get all gist 
run-name: ${{ github.actor }} - example gh api get gist
on: workflow_dispatch
jobs:
  # - - - - - - - - - - - - - - - - - - - - - -
  # use the gh api to get all gists and store the response in a json file
  main:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: |
          RESPONSE_API=$(curl -L\
            -H "Accept: application/vnd.github+json"\
            -H "Authorization: token ${{ secrets.PAT }}"\
            -H "X-GitHub-Api-Version: 2022-11-28"\
            https://api.github.com/users/tmslpm/gists)
          mkdir -p result
          echo $RESPONSE_API > ./result/gist_data.last.json
          git config --local user.email "gh-actions@users.noreply.github.com" && git config --local user.name "gh-actions-bot"
          git add . && git commit -m "commit by gh actions"
      - name: Make Github push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main