# name: Hello World - Gradle
# category: hello-world
# description: This action is just for demonstration purposes (or a template), it shows how to execute a Gradle script in Github action.
name: 😻 Hello World - Gradle
run-name: ${{ github.actor }} - print Hello World !
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.1
      - name: Make gradlew executable on github action (or perm denied) and executed the game
        run: |
          echo disabled, repos not implemente gradlew...
          # chmod +x ./gradlew 
          # ./gradlew build