# name: Hello World - nodeJs
# description: This action is just for demonstration purposes (or a template), it shows how to execute a nodeJS script in Github action.
name: 😻 Hello World - nodeJs
run-name: ${{ github.actor }} - print Hello World !
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
      - name: "use node for execute script file or inline code"
        run: |
          node -e console.log('hello world')