name: 😻 hello world - nodejs
run-name: ${{ github.actor }} - print Hello World !
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
          cache: "npm"
      - name: "use node for execute script file or inline code"
        run: |
          node -e console.log('hello world')