# name: Hello World - nodeJs
# category: hello-world
# description: This action is just for demonstration purposes (or a template), it shows how to execute a nodeJS script in Github action.
name: 😻 Hello World - nodeJs
run-name: ${{ github.actor }} - print Hello World !
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
      - name: "use node for execute script file or inline code"
        run: |
          node -e "console.log('hello world')"
      - name: "multiple line"
        run: |
          node - << 'EOF'
          console.log("hello wolrd! 0");
          console.log("hello wolrd! 1");
          console.log("hello wolrd! 2");
          EOF