name: ▶️ push to main
run-name: ${{ github.actor }} - execute add ., commit and push to main branch
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make Github commit
        run: |
          mkdir -p result
          mv *.json /result
          git config --local user.email "gh-actions@users.noreply.github.com" && git config --local user.name "gh-actions-bot"
          git add . && git commit -m "commit by gh actions"
      - name: Make Github push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main