name: run game Y 1
run-name: ${{ github.actor }} - build

on: 
  workflow_dispatch:

jobs:
    build: 
      runs-on: ubuntu-latest
      permissions: read-all
      steps:
        - uses: actions/checkout@v4
        - run: |
            RESPONSE_API=$(curl -L\
              -H "Accept: application/vnd.github+json"\
              -H "Authorization: token ${{ secrets.PAT }}"\
              -H "X-GitHub-Api-Version: 2022-11-28"\
              https://api.github.com/users/tmslpm/gists)
            echo $RESPONSE_API
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}