name: run game Y 1
run-name: ${{ github.actor }} - build

on: 
  workflow_dispatch:

jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: | 
            gh api /gists
            echo success
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}